package uk.bl.iiifimageservice.service;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import uk.bl.iiifimageservice.domain.ImageFormat;
import uk.bl.iiifimageservice.domain.ImageMetadata;
import uk.bl.iiifimageservice.domain.ImageQuality;
import uk.bl.iiifimageservice.util.TextDisplayHelper;

/**
 * Extracts image metadata from the log file generated by kdu_expand
 * 
 * 
 * @author pblake
 * 
 */
@Service
public class LogFileExtractor {

    private final static Pattern sizePattern = Pattern.compile("Ssize=\\{(\\d+),(\\d+)\\}");
    private final static Pattern tilesPattern = Pattern.compile("Stiles=\\{(\\d+),(\\d+)\\}");
    private final static Pattern levelsPattern = Pattern.compile("Clevels=(\\d+)");
    private static final Logger log = LoggerFactory.getLogger(LogFileExtractor.class);

    @Resource
    private TextDisplayHelper textDisplayHelper;

    public ImageMetadata extractImageMetadata(String identifier, String logFile, String complianceLevel) {

        ImageMetadata imageMetadata = new ImageMetadata();
        imageMetadata.setIdentifier(identifier);

        Matcher sizeMatcher = sizePattern.matcher(logFile);
        if (sizeMatcher.find()) {
            imageMetadata.setHeight(Integer.valueOf(sizeMatcher.group(1)));
            imageMetadata.setWidth(Integer.valueOf(sizeMatcher.group(2)));
        }

        Matcher tilesMatcher = tilesPattern.matcher(logFile);
        if (tilesMatcher.find()) {
            imageMetadata.setTileHeight(Integer.valueOf(tilesMatcher.group(1)));
            imageMetadata.setTileWidth(Integer.valueOf(tilesMatcher.group(2)));
        }

        // scale_factors is value of Clevels from log file
        imageMetadata.setScaleFactors(extractScaleFactors(logFile));

        imageMetadata.setFormats(textDisplayHelper.getDisplayValuesFrom(ImageFormat.values()));

        imageMetadata.setQualities(textDisplayHelper.getDisplayValuesFrom(ImageQuality.values()));

        imageMetadata.setProfile(complianceLevel);

        log.debug("Scraped from log file [" + imageMetadata + "]");
        return imageMetadata;
    }

    private List<Integer> extractScaleFactors(String logFile) {

        Integer levels = null;
        Matcher levelsMatcher = levelsPattern.matcher(logFile);
        if (levelsMatcher.find()) {
            levels = Integer.valueOf(levelsMatcher.group(1)) - 1;
        }

        List<Integer> scaleFactors = new ArrayList<>();
        for (int i = 0; i < levels; i++) {
            scaleFactors.add((int) Math.pow(2, i));

        }

        return scaleFactors;

    }

}
